# Generated by Django 5.1.7 on 2025-03-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Variable",
            fields=[
                ("v_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                (
                    "distribution",
                    models.CharField(
                        choices=[("Normal", "Normal"), ("Uniform", "Uniform")],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("mean", models.FloatField(default=0.0)),
                ("sigma", models.FloatField(default=1.0)),
                ("lower", models.FloatField(default=0.0)),
                ("upper", models.FloatField(default=1.0)),
            ],
        ),
    ]
