# Generated by Django 5.1.7 on 2025-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variable",
            name="v_index",
            field=models.IntegerField(db_default=0),
        ),
    ]
