# Generated by Django 5.1.7 on 2025-04-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0002_variable_v_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.CheckConstraint(
                condition=models.Q(("distribution__in", ["Normal", "Uniform"])),
                name="variables_check_distribution",
            ),
        ),
    ]
