# Generated by Django 5.1.7 on 2025-04-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_variable_variables_check_distribution"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="variable",
            name="variables_check_distribution",
        ),
        migrations.AddConstraint(
            model_name="variable",
            constraint=models.CheckConstraint(
                condition=models.Q(("distribution__in", ["Normal", "Distribution"])),
                name="variables_check_distribution",
            ),
        ),
    ]
