CREATE TABLE IF NOT EXISTS points(
    p_id INTEGER PRIMARY KEY NOT NULL,
    p_index INTEGER NOT NULL DEFAULT -1,
    p_name TEXT NOT NULL DEFAULT "point",
    x REAL NOT NULL DEFAULT 0.0,
    y REAL NOT NULL DEFAULT 0.0,
    z REAL NOT NULL DEFAULT 0.0
);
