CREATE TABLE IF NOT EXISTS line(
    l_id INTEGER PRIMARY KEY NOT NULL,
    l_index INTEGER NOT NULL DEFAULT -1,
    l_name TEXT NOT NULL DEFAULT "line"
);

CREATE TABLE IF NOT EXISTS line_tree(
    l_id INTEGER PRIMARY KEY REFERENCES line(l_id) ON DELETE CASCADE,
    is_expanded BOOLEAN NOT NULL DEFAULT 1
);


CREATE TABLE IF NOT EXISTS point(
    p_id INTEGER PRIMARY KEY NOT NULL,
    l_id INTEGER REFERENCES line(l_id) ON DELETE CASCADE,
    p_index INTEGER NOT NULL DEFAULT -1,
    p_name TEXT NOT NULL DEFAULT "point",
    x REAL NOT NULL DEFAULT 0.0,
    y REAL NOT NULL DEFAULT 0.0,
    z REAL NOT NULL DEFAULT 0.0
);
