CREATE TABLE cube(
    c_id INTEGER PRIMARY KEY NOT NULL,
    name TEXT NOT NULL DEFAULT "cube",
    p_1_x FLOAT NOT NULL DEFAULT 0.0,
    p_1_y FLOAT NOT NULL DEFAULT 0.0,
    p_1_z FLOAT NOT NULL DEFAULT 0.0,
    p_2_x FLOAT NOT NULL DEFAULT 0.0,
    p_2_y FLOAT NOT NULL DEFAULT 0.0,
    p_2_z FLOAT NOT NULL DEFAULT 0.0,
    entry TEXT DEFAULT NULL
);