CREATE TABLE IF NOT EXISTS point(
    p_id INTEGER PRIMARY KEY NOT NULL,
    p_order INTEGER DEFAULT 0,
    p_name TEXT NOT NULL DEFAULT "point",
    x REAL NOT NULL DEFAULT 0.0,
    y REAL NOT NULL DEFAULT 0.0
);