name: Linting

on: push

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cmd: black
            args: "--check"
          - cmd: isort
            args: "--check"
          - cmd: ruff
            args: ""
          - cmd: mypy
            args: ""
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.11
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install maestro
        run: uv install maestro@git+https://github.com/ehmoussi/maestro.git
      - name: Install composeui
        run: uv sync --extra dev --extra all
      - name: Install composeui
        run: uv sync --extra dev --extra all
      - name: Run  ${{ matrix.cmd }}
        run: uv run maestro  ${{ matrix.cmd }}  ${{ matrix.args }}
