name: Tests (>= 3.7)

on: push

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - name: Install xclip and xvfb
        run: sudo apt install -y xclip xvfb
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Install maestro
        run: uv add maestro@git+https://github.com/ehmoussi/maestro.git
      - name: Install composeui
        run: uv sync --extra dev --extra all
      - name: Run the tests
        run: xvfb-run --auto-servernum uv run maestro test
