name: Tests (== 3.6)

on: push

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Install xclip and xvfb
        run: sudo apt install -y xclip xvfb
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.6"
          cache: "pip"
      - name: Install maestro
        run: python -m pip install maestro@git+https://github.com/ehmoussi/maestro.git
      - name: Install composeui
        run: python -m pip install -e .[dev,all]
      - name: Run the tests
        run: xvfb-run --auto-servernum maestro test
